title: "疎行列とベクトルを掛けたい貴方に"
summary: "著者が数値計算の一大ジャンルだと勝手に思っている疎行列ベクトル積について解説します．疎行列を制するものは数値計算を制するような気がします．なお，解説にはC/C++を使います．無償ですが，何かの役に立った人はdonateしてくれると喜びます．"
topics: ["数値計算"]
published: false
allow_override: true
price: 0
chapters:
  - about
  - intro
  - what_to_use
  - dns
  - matrix_market
  - coo
  - crs
  - spmv_hpc
  - sparse_blas
