title: "疎行列とベクトルを掛けたい貴方に"
summary: "疎行列とベクトルを掛けたい貴方に"
topics: ["数値計算"]
published: false
allow_override: true
price: 0
chapters:
  - about
  - intro
  - what_to_use
  - sparse_blas
  - coo
  - crs
  - matrix_market
